### ISSUE TITLE
Socket connection

### ISSUE THREAD

**Issue by qriff** [daftaupe/munin-plugins-tor#2]
For http://munin-monitoring.org/wiki/PluginDebugging set in /etc/munin/plugin-conf.d/[tor_ | munin-node]

```
[tor_*]
user tor
group tor
```
or

```
[tor_*]
user debian-tor
group debian-tor
```

as Munin doesn't run as root and the socket /var/run/tor/control is owned by the tor daemon user.

```
[tor_*]
env.connectmethod socket
# env.socket /var/run/tor/control
```

**Comment by daftaupe** [comment]
Hello,

thanks for sharing.
Actually I don't run tor under Debian. So I have :
```
[tor_*]
env.user toranon
```

Anyway, maybe I should start a wiki page ? To gather this kind of information, I felt like the README/intro page felt a bit confusing.

**Comment by qriff** [comment]
Don't know if there is a need for wiki, just elaborate the README to a more progressive form, including the plugin test example with munin-run tor_bandwidth . Your one file integration did enough to get it in production reasonably, maybe publish the plugin to https://github.com/munin-monitoring/contrib/tree/master/plugins/tor etc.

**Comment by daftaupe** [comment]
I will try to modify the README to be more like a procedure to follow as you suggest and also how to test that the plugins are working.

**Comment by daftaupe** [comment]
@qriff , I've tried to write a better README file, what do you think of #3 ?

**Comment by daftaupe** [comment]
I'm closing it now, comment if needed.
